a=input("Enter text to write to the file;")
f=open("output.txt","w")
f.write(a + "\n")
print("Data sucessfully written to the output.txt")
b=input("Enter additional text to append:")
f.write(b)
print("Data sucessfully appended")
f.close()
print("The final contents of output.txt:")
f=open("output.txt","r")
print(f.read())
f.close()